name: Copy to Repo B job
on:
  push:
    branches: main

    paths:
      - 'test-folder/**'
      - '.github/workflows/copy.yml'

jobs:
  copy:
    name: Copy job
    runs-on: ubuntu-latest
    steps:
      - name: Copy test folder items into Repo-B
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: test-folder/.
          dst_path: test-folder/.
          dst_owner: fariskamaludin-skymind
          dst_repo_name: Repo-B
          src_branch: main
          dst_branch: test
          clean: true
