name: Copy to Repo B job
on: push

jobs:
  copy:
    name: Copy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: ls -la

      #- name: Copy test folder items into Repo-B
       # uses: andstor/copycat-action@v3
        #with:
         # personal_token: ${{ secrets.PERSONAL_TOKEN }}
          #src_path: /test-folder/.
          #dst_path: /test-folder/.
          #dst_owner: fariskamaludin-skymind
          #dst_repo_name: Repo-B
          #src_branch: main
          #dst_branch: main
          #clean: true
